#pragma config(Sensor, S1,     acc,            sensorI2CHiTechnicAccel)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "AdvancedSensors.c"
task main()
{
	int ax;
	int ay;
	int az;
	while(true){
		getAccel(acc,ax,ay,az);
		nxtDisplayCenteredBigTextLine(0,"%d",ax);
			nxtDisplayCenteredBigTextLine(2,"%d",ay);
				nxtDisplayCenteredBigTextLine(4,"%d",az);
	}
}
