#pragma config(Sensor, S1,     l,              sensorTouch)
#pragma config(Sensor, S2,     f,              sensorTouch)
#pragma config(Sensor, S3,     b,              sensorTouch)
#pragma config(Sensor, S4,     r,              sensorTouch)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn();
	int min=500;
	int max=1000;
task main()
{
	while(true){
		motor[left]=25;
		motor[right]=25;
		while(SensorValue[f]==0&&SensorValue[r]0=0&&SensorValue[b]==0&&SensorValue[l]==0){
	//		nxtDisplayCenteredBigTextLine(0,"%d",SensorValue[f]);
		//	nxtDisplayCenteredBigTextLine(2,"%d",SensorValue[r]);
			//nxtDisplayCenteredBigTextLine(4,"%d",SensorValue[b]);
		//	nxtDisplayCenteredBigTextLine(6,"%d",SensorValue[l]);
		}
		if(SensorValue[f]>0){
				motor[left]=-50;
				motor[right]=-50;
				wait1Msec(1000);
				motor[left]=0;
				motor[right]=0;
		}
		if(SensorValue[b]>0){
				motor[left]=50;
				motor[right]=50;
				wait1Msec(1000);
				motor[left]=0;
				motor[right]=0;
		}
		if(SensorValue[r]>0){
			motor[right]=-50;
			wait1Msec(250);
			motor[right]=0;
			wait1Msec(200);
				motor[left]=-50;
				motor[right]=-50;
				wait1Msec(750);
				motor[left]=0;
				motor[right]=0;
			//right back
		}
		if(SensorValue[l]>0){
				motor[left]=-50;
				wait1Msec(250);
				motor[left]=0;
					wait1Msec(200);
				motor[left]=-50;
				motor[right]=-50;
				wait1Msec(750);
				motor[left]=0;
				motor[right]=0;
		}
		wait1Msec(500);
		turn();
		wait1Msec(500);
	}
}
void turn(){
		motor[left]=50;
		motor[right]=-50;
		wait1Msec((rand() % (max-min)) + min);
		motor[right]=0;
		motor[left]=0;
}
