#pragma config(Sensor, S1,     color,          sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
	nxtDisplayCenteredBigTextLine(0,"%d",SensorValue[color]);
}



}
