#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
task main()
{
	while(true){
		getJoystickSettings(joystick);
		motor[left]=joystick.joy1_y1;
		motor[right]=joystick.joy1_y2;
	}
}
