#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

volatile float theta=0;
float offset;
task G(){
	ClearTimer(T1);
	while(true){
		theta+=(SensorValue[gyro]-offset)*time1[T1]/1000;
		ClearTimer(T1);
		wait1Msec(10);
	}
}
task main()
{
	wait1Msec(1000);
offset=SensorValue[gyro];
StartTask(G);
motor[left]=-5;
motor[right]=5;
bool l=false;
	while(true){
		nxtDisplayCenteredBigTextLine(2,"%d",(int)theta);
		wait1Msec(100);
		if(l){
			motor[left]=5;
			motor[right]=-5;
		}
		else{
			motor[left]=-5;
			motor[right]=5;
		}
		if(theta>360&&l)l=false;
		if(theta<-360&&!l)l=true;
	}
}
