#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     north,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     south,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     east,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     west,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c";
#include "includes/vector.c"

task main()
{
	int tmp;
	//int tmp2;
while(true)
{
	getJoystickSettings(joystick);

	tmp = joystick.joy1_x2;
	motor[east] = tmp;
	motor[west] = -tmp;
	tmp = joystick.joy1_y2;
	motor[north] = tmp;
	motor[south] = -tmp;

	tmp = joystick.joy1_x1;
	motor[north] = tmp;
	motor[south] = tmp;
	motor[east] = tmp;
	motor[west] = tmp;
}


}
