#pragma config(Sensor, S1,     ir,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true){
	nxtDisplayCenteredBigTextLine(0,"%d",SensorValue[ir]);
	wait1Msec(100);
}


}
