#pragma config(Sensor, S3,     light,          sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		nxtDisplayCenteredBigTextLine(2,"%d",SensorValue[light]);
		wait1Msec(100);
	}



}
