#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int count=0;
int i=0;
task main()
{
	const int THRESH=50;
	const int speed=25;
	for(i=0;i<5;i++){
		count=0;
		nMotorEncoder[left]=0;
		nMotorEncoder[right]=0;
		motor[left]=speed;
		motor[right]=speed;
		for(;count<=i;count++){
			while(SensorValue[light]>THRESH)wait1Msec(25);
			while(SensorValue[light]<THRESH)wait1Msec(25);
		}
		motor[left]=-speed;
		motor[right]=-speed;
		while(nMotorEncoder[right]>0);
	}
}
