#pragma config(Sensor, S1,     mag,            sensorHiTechnicMagnetic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true){
	nxtDisplayCenteredBigTextLine(2,"%d",SensorValue[mag]);
	wait1Msec(100);
}


}
