#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     mag,            sensorHiTechnicMagnetic)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    arm,                  tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task bt(){
	while(true){
		nxtDisplayCenteredBigTextLine(2,"%d",SensorValue[mag]);
		if(abs(660-SensorValue[mag])>5 && !bSoundActive)PlaySound(soundBeepBeep);
		wait1msec(1000);
	}
}
task main()
{
	waitForStart();
	bDisplayDiagnostics=false;
StartTask(bt);
	nMotorEncoder[left]=0;
	nMotorEncoder[right]=0;
	while(true){
		getJoystickSettings(joystick);
		int lm=joystick.joy1_y1;
		int rm=joystick.joy1_y2;
		if(joy1Btn(3)==1){
				motor[left]=-10;
			motor[right]=10;
		}else if(joy1Btn(1)==1){
			motor[left]=10;
			motor[right]=-10;
		}
		else if(joy1Btn(5)==1){
			motor[left]=-lm/4;
			motor[right]=lm/4;
		}
		else{
			motor[left]=(abs(lm)>10)?-lm:0;
			motor[right]=(abs(rm)>10)?rm:0;
		}

		if(joy1Btn(4)==1)servo[arm]=ServoValue[arm]-1;
		if(joy1Btn(2)==1)servo[arm]=ServoValue[arm]+1;
	}


}
