#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     back,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     front,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     head,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
task main()
{
	while(true){
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_x1)<10){//move
			motor[left]=-joystick.joy1_y2;
			motor[right]=joystick.joy1_y2;
			motor[front]=joystick.joy1_x2;
			motor[back]=-joystick.joy1_x2;
		}
		else{//rotate
			int speed=joystick.joy1_x1;
			motor[left]=speed;
			motor[right]=speed;
			motor[back]=speed;
			motor[front]=speed;
		}
		if(joy1Btn(6)==1){
			motor[head]=40;
		}
		else if(joy1Btn(5)==1){
			motor[head]=-40;
		}
		else{
			motor[head]=0;
		}
	}
}
