#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     HTPB,           sensorI2CCustom9V)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "HTPB.h"
const double sonarConversion=1.9859;
task main()
{
	while(true){//6.4mV/in=.006445V/in
		//1024/3.3=.3103/mV
		int i=readAnalogInput(HTPB,1);
		nxtDisplayCenteredBigTextLine(3,"%d",i);
		double mv=.3101*i;
		double dist=i*6.4;//mv->in
		nxtDisplayCenteredBigTextLine(5,"%d",dist);
	}
}
