#pragma config(Sensor, S1,     f,              sensorLightActive)
#pragma config(Sensor, S2,     b,              sensorCOLORFULL)
#pragma config(Sensor, S3,     r,              sensorLightActive)
#pragma config(Sensor, S4,     l,              sensorLightActive)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void turn();
	int min=500;
	int max=1000;
	task graph(){
		while(true){
			/*
			nxtDisplayCenteredBigTextLine(0,"f: %d",SensorValue[f]);
			nxtDisplayCenteredBigTextLine(2,"b: %d",SensorValue[b]);
			nxtDisplayCenteredBigTextLine(4,"r: %d",SensorValue[r]);
			nxtDisplayCenteredBigTextLine(6,"l: %d",SensorValue[l]);
			*/
			nxtDisplayCenteredBigTextLine(2,"HELLO!");
			wait1Msec(100);
		}
	}
task main()
{StartTask(graph);
	while(true){
		motor[left]=45;
		motor[right]=45;
		while(SensorValue[f]>=40&&SensorValue[r]>=40&&SensorValue[b]>1&&SensorValue[l]>=40){

		}
		if(SensorValue[f]<40){
				motor[left]=50;
				motor[right]=50;
				wait1Msec(1000);
				motor[left]=0;
				motor[right]=0;
		}
		if(SensorValue[b]<=1){
				motor[left]=-50;
				motor[right]=-50;
				wait1Msec(1000);
				motor[left]=0;
				motor[right]=0;
		}
		if(SensorValue[r]<40){
			motor[right]=-50;
			wait1Msec(250);
			motor[right]=0;
		wait1Msec(200);
				motor[left]=-50;
				motor[right]=-50;
				wait1Msec(750);
				motor[left]=0;
				motor[right]=0;
			//right back
		}
		if(SensorValue[l]<40){
				motor[left]=-50;
				wait1Msec(250);
				motor[left]=0;
					wait1Msec(200);
				motor[left]=-50;
				motor[right]=-50;
				wait1Msec(750);
				motor[left]=0;
				motor[right]=0;
		}
		wait1Msec(500);
		turn();
		wait1Msec(500);
	}
}
void turn(){
		int r=(rand()%2==1)?1:-1;
		motor[left]=50*r;
		motor[right]=-50*r;
		wait1Msec((rand() % (max-min)) + min);
		motor[right]=0;
		motor[left]=0;
}
