#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		int sv=SensorValue[ir];
		motor[motorA]=(sv<6)?50:0;
		motor[motorB]=(sv>4)?50:0;
	}



}
